/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HealthRouteImport } from './routes/health'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ApiDashboardAnalyticsRouteImport } from './routes/api/dashboard-analytics'
import { Route as ApiEmailLogsRouteImport } from './routes/api/email-logs'
import { Route as ApiGmailAccountsRouteImport } from './routes/api/gmail-accounts'
import { Route as ApiLoginRouteImport } from './routes/api/login'
import { Route as ApiLogoutRouteImport } from './routes/api/logout'
import { Route as ApiMailSendersRouteImport } from './routes/api/mail-senders'
import { Route as ApiMeRouteImport } from './routes/api/me'
import { Route as ApiRegisterRouteImport } from './routes/api/register'
import { Route as ApiSendEmailRouteImport } from './routes/api/send-email'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardApprovalsRouteImport } from './routes/dashboard/approvals'
import { Route as DashboardEmailLogsRouteImport } from './routes/dashboard/email-logs'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardSendEmailRouteImport } from './routes/dashboard/send-email'
import { Route as DashboardSendersRouteImport } from './routes/dashboard/senders'
import { Route as DashboardUsersRouteImport } from './routes/dashboard/users'
import { Route as ApiAdminApprovalsRouteImport } from './routes/api/admin.approvals'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin.users'
import { Route as ApiGmailAccountsIdRouteImport } from './routes/api/gmail-accounts/$id'
import { Route as ApiMailSendersIdRouteImport } from './routes/api/mail-senders/$id'
import { Route as ApiAdminUsersIdRouteImport } from './routes/api/admin.users/$id'
import { Route as ApiGmailOauthCallbackRouteImport } from './routes/api/gmail.oauth.callback'
import { Route as ApiGmailOauthStartRouteImport } from './routes/api/gmail.oauth.start'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardAnalyticsRoute = ApiDashboardAnalyticsRouteImport.update({
  id: '/api/dashboard-analytics',
  path: '/api/dashboard-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailLogsRoute = ApiEmailLogsRouteImport.update({
  id: '/api/email-logs',
  path: '/api/email-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGmailAccountsRoute = ApiGmailAccountsRouteImport.update({
  id: '/api/gmail-accounts',
  path: '/api/gmail-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoginRoute = ApiLoginRouteImport.update({
  id: '/api/login',
  path: '/api/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLogoutRoute = ApiLogoutRouteImport.update({
  id: '/api/logout',
  path: '/api/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMailSendersRoute = ApiMailSendersRouteImport.update({
  id: '/api/mail-senders',
  path: '/api/mail-senders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeRoute = ApiMeRouteImport.update({
  id: '/api/me',
  path: '/api/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegisterRoute = ApiRegisterRouteImport.update({
  id: '/api/register',
  path: '/api/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendEmailRoute = ApiSendEmailRouteImport.update({
  id: '/api/send-email',
  path: '/api/send-email',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApprovalsRoute = DashboardApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEmailLogsRoute = DashboardEmailLogsRouteImport.update({
  id: '/email-logs',
  path: '/email-logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSendEmailRoute = DashboardSendEmailRouteImport.update({
  id: '/send-email',
  path: '/send-email',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSendersRoute = DashboardSendersRouteImport.update({
  id: '/senders',
  path: '/senders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiAdminApprovalsRoute = ApiAdminApprovalsRouteImport.update({
  id: '/api/admin/approvals',
  path: '/api/admin/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGmailAccountsIdRoute = ApiGmailAccountsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiGmailAccountsRoute,
} as any)
const ApiMailSendersIdRoute = ApiMailSendersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiMailSendersRoute,
} as any)
const ApiAdminUsersIdRoute = ApiAdminUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminUsersRoute,
} as any)
const ApiGmailOauthCallbackRoute = ApiGmailOauthCallbackRouteImport.update({
  id: '/api/gmail/oauth/callback',
  path: '/api/gmail/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGmailOauthStartRoute = ApiGmailOauthStartRouteImport.update({
  id: '/api/gmail/oauth/start',
  path: '/api/gmail/oauth/start',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/dashboard-analytics': typeof ApiDashboardAnalyticsRoute
  '/api/email-logs': typeof ApiEmailLogsRoute
  '/api/gmail-accounts': typeof ApiGmailAccountsRouteWithChildren
  '/api/login': typeof ApiLoginRoute
  '/api/logout': typeof ApiLogoutRoute
  '/api/mail-senders': typeof ApiMailSendersRouteWithChildren
  '/api/me': typeof ApiMeRoute
  '/api/register': typeof ApiRegisterRoute
  '/api/send-email': typeof ApiSendEmailRoute
  '/dashboard/approvals': typeof DashboardApprovalsRoute
  '/dashboard/email-logs': typeof DashboardEmailLogsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/send-email': typeof DashboardSendEmailRoute
  '/dashboard/senders': typeof DashboardSendersRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/admin/approvals': typeof ApiAdminApprovalsRoute
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/gmail-accounts/$id': typeof ApiGmailAccountsIdRoute
  '/api/mail-senders/$id': typeof ApiMailSendersIdRoute
  '/api/admin/users/$id': typeof ApiAdminUsersIdRoute
  '/api/gmail/oauth/callback': typeof ApiGmailOauthCallbackRoute
  '/api/gmail/oauth/start': typeof ApiGmailOauthStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/dashboard-analytics': typeof ApiDashboardAnalyticsRoute
  '/api/email-logs': typeof ApiEmailLogsRoute
  '/api/gmail-accounts': typeof ApiGmailAccountsRouteWithChildren
  '/api/login': typeof ApiLoginRoute
  '/api/logout': typeof ApiLogoutRoute
  '/api/mail-senders': typeof ApiMailSendersRouteWithChildren
  '/api/me': typeof ApiMeRoute
  '/api/register': typeof ApiRegisterRoute
  '/api/send-email': typeof ApiSendEmailRoute
  '/dashboard/approvals': typeof DashboardApprovalsRoute
  '/dashboard/email-logs': typeof DashboardEmailLogsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/send-email': typeof DashboardSendEmailRoute
  '/dashboard/senders': typeof DashboardSendersRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/admin/approvals': typeof ApiAdminApprovalsRoute
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/gmail-accounts/$id': typeof ApiGmailAccountsIdRoute
  '/api/mail-senders/$id': typeof ApiMailSendersIdRoute
  '/api/admin/users/$id': typeof ApiAdminUsersIdRoute
  '/api/gmail/oauth/callback': typeof ApiGmailOauthCallbackRoute
  '/api/gmail/oauth/start': typeof ApiGmailOauthStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/dashboard-analytics': typeof ApiDashboardAnalyticsRoute
  '/api/email-logs': typeof ApiEmailLogsRoute
  '/api/gmail-accounts': typeof ApiGmailAccountsRouteWithChildren
  '/api/login': typeof ApiLoginRoute
  '/api/logout': typeof ApiLogoutRoute
  '/api/mail-senders': typeof ApiMailSendersRouteWithChildren
  '/api/me': typeof ApiMeRoute
  '/api/register': typeof ApiRegisterRoute
  '/api/send-email': typeof ApiSendEmailRoute
  '/dashboard/approvals': typeof DashboardApprovalsRoute
  '/dashboard/email-logs': typeof DashboardEmailLogsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/send-email': typeof DashboardSendEmailRoute
  '/dashboard/senders': typeof DashboardSendersRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/admin/approvals': typeof ApiAdminApprovalsRoute
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/gmail-accounts/$id': typeof ApiGmailAccountsIdRoute
  '/api/mail-senders/$id': typeof ApiMailSendersIdRoute
  '/api/admin/users/$id': typeof ApiAdminUsersIdRoute
  '/api/gmail/oauth/callback': typeof ApiGmailOauthCallbackRoute
  '/api/gmail/oauth/start': typeof ApiGmailOauthStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/health'
    | '/login'
    | '/register'
    | '/api/dashboard-analytics'
    | '/api/email-logs'
    | '/api/gmail-accounts'
    | '/api/login'
    | '/api/logout'
    | '/api/mail-senders'
    | '/api/me'
    | '/api/register'
    | '/api/send-email'
    | '/dashboard/approvals'
    | '/dashboard/email-logs'
    | '/dashboard/profile'
    | '/dashboard/send-email'
    | '/dashboard/senders'
    | '/dashboard/users'
    | '/dashboard/'
    | '/api/admin/approvals'
    | '/api/admin/users'
    | '/api/gmail-accounts/$id'
    | '/api/mail-senders/$id'
    | '/api/admin/users/$id'
    | '/api/gmail/oauth/callback'
    | '/api/gmail/oauth/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/login'
    | '/register'
    | '/api/dashboard-analytics'
    | '/api/email-logs'
    | '/api/gmail-accounts'
    | '/api/login'
    | '/api/logout'
    | '/api/mail-senders'
    | '/api/me'
    | '/api/register'
    | '/api/send-email'
    | '/dashboard/approvals'
    | '/dashboard/email-logs'
    | '/dashboard/profile'
    | '/dashboard/send-email'
    | '/dashboard/senders'
    | '/dashboard/users'
    | '/dashboard'
    | '/api/admin/approvals'
    | '/api/admin/users'
    | '/api/gmail-accounts/$id'
    | '/api/mail-senders/$id'
    | '/api/admin/users/$id'
    | '/api/gmail/oauth/callback'
    | '/api/gmail/oauth/start'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/health'
    | '/login'
    | '/register'
    | '/api/dashboard-analytics'
    | '/api/email-logs'
    | '/api/gmail-accounts'
    | '/api/login'
    | '/api/logout'
    | '/api/mail-senders'
    | '/api/me'
    | '/api/register'
    | '/api/send-email'
    | '/dashboard/approvals'
    | '/dashboard/email-logs'
    | '/dashboard/profile'
    | '/dashboard/send-email'
    | '/dashboard/senders'
    | '/dashboard/users'
    | '/dashboard/'
    | '/api/admin/approvals'
    | '/api/admin/users'
    | '/api/gmail-accounts/$id'
    | '/api/mail-senders/$id'
    | '/api/admin/users/$id'
    | '/api/gmail/oauth/callback'
    | '/api/gmail/oauth/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  HealthRoute: typeof HealthRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiDashboardAnalyticsRoute: typeof ApiDashboardAnalyticsRoute
  ApiEmailLogsRoute: typeof ApiEmailLogsRoute
  ApiGmailAccountsRoute: typeof ApiGmailAccountsRouteWithChildren
  ApiLoginRoute: typeof ApiLoginRoute
  ApiLogoutRoute: typeof ApiLogoutRoute
  ApiMailSendersRoute: typeof ApiMailSendersRouteWithChildren
  ApiMeRoute: typeof ApiMeRoute
  ApiRegisterRoute: typeof ApiRegisterRoute
  ApiSendEmailRoute: typeof ApiSendEmailRoute
  ApiAdminApprovalsRoute: typeof ApiAdminApprovalsRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRouteWithChildren
  ApiGmailOauthCallbackRoute: typeof ApiGmailOauthCallbackRoute
  ApiGmailOauthStartRoute: typeof ApiGmailOauthStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard-analytics': {
      id: '/api/dashboard-analytics'
      path: '/api/dashboard-analytics'
      fullPath: '/api/dashboard-analytics'
      preLoaderRoute: typeof ApiDashboardAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email-logs': {
      id: '/api/email-logs'
      path: '/api/email-logs'
      fullPath: '/api/email-logs'
      preLoaderRoute: typeof ApiEmailLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gmail-accounts': {
      id: '/api/gmail-accounts'
      path: '/api/gmail-accounts'
      fullPath: '/api/gmail-accounts'
      preLoaderRoute: typeof ApiGmailAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/login': {
      id: '/api/login'
      path: '/api/login'
      fullPath: '/api/login'
      preLoaderRoute: typeof ApiLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/logout': {
      id: '/api/logout'
      path: '/api/logout'
      fullPath: '/api/logout'
      preLoaderRoute: typeof ApiLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mail-senders': {
      id: '/api/mail-senders'
      path: '/api/mail-senders'
      fullPath: '/api/mail-senders'
      preLoaderRoute: typeof ApiMailSendersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me': {
      id: '/api/me'
      path: '/api/me'
      fullPath: '/api/me'
      preLoaderRoute: typeof ApiMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/register': {
      id: '/api/register'
      path: '/api/register'
      fullPath: '/api/register'
      preLoaderRoute: typeof ApiRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-email': {
      id: '/api/send-email'
      path: '/api/send-email'
      fullPath: '/api/send-email'
      preLoaderRoute: typeof ApiSendEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/approvals': {
      id: '/dashboard/approvals'
      path: '/approvals'
      fullPath: '/dashboard/approvals'
      preLoaderRoute: typeof DashboardApprovalsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/email-logs': {
      id: '/dashboard/email-logs'
      path: '/email-logs'
      fullPath: '/dashboard/email-logs'
      preLoaderRoute: typeof DashboardEmailLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/send-email': {
      id: '/dashboard/send-email'
      path: '/send-email'
      fullPath: '/dashboard/send-email'
      preLoaderRoute: typeof DashboardSendEmailRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/senders': {
      id: '/dashboard/senders'
      path: '/senders'
      fullPath: '/dashboard/senders'
      preLoaderRoute: typeof DashboardSendersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/admin/approvals': {
      id: '/api/admin/approvals'
      path: '/api/admin/approvals'
      fullPath: '/api/admin/approvals'
      preLoaderRoute: typeof ApiAdminApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gmail-accounts/$id': {
      id: '/api/gmail-accounts/$id'
      path: '/$id'
      fullPath: '/api/gmail-accounts/$id'
      preLoaderRoute: typeof ApiGmailAccountsIdRouteImport
      parentRoute: typeof ApiGmailAccountsRoute
    }
    '/api/mail-senders/$id': {
      id: '/api/mail-senders/$id'
      path: '/$id'
      fullPath: '/api/mail-senders/$id'
      preLoaderRoute: typeof ApiMailSendersIdRouteImport
      parentRoute: typeof ApiMailSendersRoute
    }
    '/api/admin/users/$id': {
      id: '/api/admin/users/$id'
      path: '/$id'
      fullPath: '/api/admin/users/$id'
      preLoaderRoute: typeof ApiAdminUsersIdRouteImport
      parentRoute: typeof ApiAdminUsersRoute
    }
    '/api/gmail/oauth/callback': {
      id: '/api/gmail/oauth/callback'
      path: '/api/gmail/oauth/callback'
      fullPath: '/api/gmail/oauth/callback'
      preLoaderRoute: typeof ApiGmailOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gmail/oauth/start': {
      id: '/api/gmail/oauth/start'
      path: '/api/gmail/oauth/start'
      fullPath: '/api/gmail/oauth/start'
      preLoaderRoute: typeof ApiGmailOauthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardApprovalsRoute: typeof DashboardApprovalsRoute
  DashboardEmailLogsRoute: typeof DashboardEmailLogsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSendEmailRoute: typeof DashboardSendEmailRoute
  DashboardSendersRoute: typeof DashboardSendersRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardApprovalsRoute: DashboardApprovalsRoute,
  DashboardEmailLogsRoute: DashboardEmailLogsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSendEmailRoute: DashboardSendEmailRoute,
  DashboardSendersRoute: DashboardSendersRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ApiGmailAccountsRouteChildren {
  ApiGmailAccountsIdRoute: typeof ApiGmailAccountsIdRoute
}

const ApiGmailAccountsRouteChildren: ApiGmailAccountsRouteChildren = {
  ApiGmailAccountsIdRoute: ApiGmailAccountsIdRoute,
}

const ApiGmailAccountsRouteWithChildren =
  ApiGmailAccountsRoute._addFileChildren(ApiGmailAccountsRouteChildren)

interface ApiMailSendersRouteChildren {
  ApiMailSendersIdRoute: typeof ApiMailSendersIdRoute
}

const ApiMailSendersRouteChildren: ApiMailSendersRouteChildren = {
  ApiMailSendersIdRoute: ApiMailSendersIdRoute,
}

const ApiMailSendersRouteWithChildren = ApiMailSendersRoute._addFileChildren(
  ApiMailSendersRouteChildren,
)

interface ApiAdminUsersRouteChildren {
  ApiAdminUsersIdRoute: typeof ApiAdminUsersIdRoute
}

const ApiAdminUsersRouteChildren: ApiAdminUsersRouteChildren = {
  ApiAdminUsersIdRoute: ApiAdminUsersIdRoute,
}

const ApiAdminUsersRouteWithChildren = ApiAdminUsersRoute._addFileChildren(
  ApiAdminUsersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  HealthRoute: HealthRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiDashboardAnalyticsRoute: ApiDashboardAnalyticsRoute,
  ApiEmailLogsRoute: ApiEmailLogsRoute,
  ApiGmailAccountsRoute: ApiGmailAccountsRouteWithChildren,
  ApiLoginRoute: ApiLoginRoute,
  ApiLogoutRoute: ApiLogoutRoute,
  ApiMailSendersRoute: ApiMailSendersRouteWithChildren,
  ApiMeRoute: ApiMeRoute,
  ApiRegisterRoute: ApiRegisterRoute,
  ApiSendEmailRoute: ApiSendEmailRoute,
  ApiAdminApprovalsRoute: ApiAdminApprovalsRoute,
  ApiAdminUsersRoute: ApiAdminUsersRouteWithChildren,
  ApiGmailOauthCallbackRoute: ApiGmailOauthCallbackRoute,
  ApiGmailOauthStartRoute: ApiGmailOauthStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
